#!/support/busybox sh
${@:2}
if [[ $? == 0 ]]; then touch /data/user/0/com.gnuroot.debian/support/.$1_passed; else read -rsp $'An error occurred, please try again and if it persists provide this log to the deveolper.\nPress any key to close...\n' -n1 key; touch /support/.$1_failed; fi