#!/bin/bash
cp /root/.Xauthority /home/.Xauthority
DISPLAY=localhost:51 xterm -geometry 80x24+0+0 -e exit
if [[ $? == 0 ]]; then
cp /root/.Xauthority /home/.Xauthority
DISPLAY=localhost:51 xterm -geometry 80x24+0+0 -e $@ &

blue='\033[0;34m'; NC='\033[0m'; echo -e "${blue}Killing this terminal will kill your xterm"
echo -e "${NC}"
else
rm /tmp/.X51-lock
rm /tmp/.X11-unix/X51
HOME=/root tightvncserver -geometry 1024x768 :51
cp /root/.Xauthority /home/.Xauthority
DISPLAY=localhost:51 xterm -geometry 80x24+0+0 -e $@ &

blue='\033[0;34m'; NC='\033[0m'; echo -e "${blue}Killing this terminal will kill your vnc server and xterm"
echo -e "${NC}"
fi